name: "Build Openwrt Image in Github CI With Javascript"
author: "Sirherobrine23"
description: "Create Snapshot images in Github Actions"
inputs:
  STYLE:
    description: "Debian or Termux folder style"
    required: false
    default: "debian"

  DIST:
    description: 'Name type main'
    required: true
    default: 'pages'

  DEBUG:
    description: 'Show some more content, default is false'
    required: false
    default: 'false'

  PUB_KEY:
    description: 'Public key file'
    required: false
    default: 'pub.key'

  PRIV_KEY:
    description: 'Private key file'
    required: false
    default: 'priv.key'

  KEY_ID:
    description: 'Id da chave (GPG)'
    required: false
    default:  ''

  URL_REPO: 
    description: 'Pages URL'
    required: true
    default: "https://${{ github.repository_owner }}.github.io/${{ github.repository }}"

  PASS:
    description: 'GPG key password'
    required: true
    default: ''

runs:
  using: 'node12'
  pre: 'setup.js'
  main: 'repo.js'

branding:
  icon: 'code'
  color: 'gray-dark'
